In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
## one Hot Representaion
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4100, 3840, 9883, 428],
 [4100, 3840, 9883, 8829],
 [4100, 971, 9883, 1742],
 [4938, 5912, 1280, 9729, 8582],
 [4938, 5912, 1280, 9729, 1430],
 [7172, 4100, 8867, 9883, 1147],
 [1282, 2402, 3357, 9729]]

In [8]:
## word embedding representaion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4100 3840 9883  428]
 [   0    0    0    0 4100 3840 9883 8829]
 [   0    0    0    0 4100  971 9883 1742]
 [   0    0    0 4938 5912 1280 9729 8582]
 [   0    0    0 4938 5912 1280 9729 1430]
 [   0    0    0 7172 4100 8867 9883 1147]
 [   0    0    0    0 1282 2402 3357 9729]]


In [13]:
## feature represenation
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 718ms/step


array([[[ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,
          0.01474691, -0.03771083,  0.03835496,  0.04679087,
         -0.00369809,  0.04403602],
        [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,
          0.01474691, -0.03771083,  0.03835496,  0.04679087,
         -0.00369809,  0.04403602],
        [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,
          0.01474691, -0.03771083,  0.03835496,  0.04679087,
         -0.00369809,  0.04403602],
        [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,
          0.01474691, -0.03771083,  0.03835496,  0.04679087,
         -0.00369809,  0.04403602],
        [-0.04044467,  0.02290155, -0.02451966, -0.01666266,
          0.01527548, -0.04870383,  0.02019774,  0.04846764,
          0.00256665, -0.00745717],
        [ 0.02757288,  0.03136693, -0.02017638, -0.03027786,
          0.01191711,  0.03470619,  0.00378807,  0.01518706,
         -0.01396032,  0.00400554],
        [-0.0304163 , -0.0324834 ,  0.02036596,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 4100, 3840, 9883,  428])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 52ms/step


array([[ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,  0.01474691,
        -0.03771083,  0.03835496,  0.04679087, -0.00369809,  0.04403602],
       [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,  0.01474691,
        -0.03771083,  0.03835496,  0.04679087, -0.00369809,  0.04403602],
       [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,  0.01474691,
        -0.03771083,  0.03835496,  0.04679087, -0.00369809,  0.04403602],
       [ 0.04764802,  0.03008174, -0.0049122 , -0.03817654,  0.01474691,
        -0.03771083,  0.03835496,  0.04679087, -0.00369809,  0.04403602],
       [-0.04044467,  0.02290155, -0.02451966, -0.01666266,  0.01527548,
        -0.04870383,  0.02019774,  0.04846764,  0.00256665, -0.00745717],
       [ 0.02757288,  0.03136693, -0.02017638, -0.03027786,  0.01191711,
         0.03470619,  0.00378807,  0.01518706, -0.01396032,  0.00400554],
       [-0.0304163 , -0.0324834 ,  0.02036596,  0.02028536,  0.0054886 ,
         0.03642544, -0.03591647,  0.03403619